version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-training
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data:/var/lib/grafana/data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge 